on:
  push:
    branches:
      - 'main'
  workflow_dispatch:
  schedule:
    - cron: '30 5 * * *'

name: Test container images and deploy
jobs:
  test:
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write
    with:
      should-deploy: true