on:
  workflow_dispatch:

name: Docker images

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-images:
    name: Build & push Docker images
    runs-on: ubuntu-latest

    strategy:
      matrix:
        runtime:
          - name: gtk-4.10
            gtktag: 4.10.1
            adwtag: 1.3.1
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      # seemed to be a cache workaround
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Login to GitHub Container Repository
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            ${{ matrix.runtime.name }}
            
      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          sed -i 's/%GTKTAG%/${{matrix.runtime.gtktag}}/g' gtk4-cross-base-hub/Dockerfile && sed -i 's/%ADWTAG%/${{matrix.runtime.adwtag}}/g' gtk4-cross-base-hub/Dockerfile

      - run: |
          cat gtk4-cross-base-hub/Dockerfile
          echo ${{ steps.meta.outputs.tags }}
      
      - name: Build & push the ${{ matrix.runtime.name }} image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        continue-on-error: false
        with:
          context: ./gtk4-cross-base-hub
          file: ./gtk4-cross-base-hub/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: Extract metadata (tags, labels) for Docker
        id: meta_rust
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/66Leo66/gtk4-cross
          tags: |
            rust-${{ matrix.runtime.name }}

      - name: Write the Dockerfile for the ${{ matrix.runtime.name }} runtime
        run: |
          sed -i 's/%GTKTAG%/${{matrix.runtime.name}}/g' gtk4-cross-rust/Dockerfile
      - name: Build & push the rust-${{ matrix.runtime.name }} image to Docker Hub
        uses: docker/build-push-action@v2.2.2
        continue-on-error: false
        with:
          context: ./gtk4-cross-rust
          file: ./gtk4-cross-rust/Dockerfile
          push: true
          tags: ${{ steps.meta_rust.outputs.tags }}
          labels: ${{ steps.meta_rust.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
